version: '3.8'

services:
  webapi:
    build:
      context: .
      dockerfile: DevOpsTaskApp.WebAPI/Dockerfile
    ports:
      - "8080:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
